// Theme metadata generated from netherize_editor/config/themes.
export interface ThemeDef { id: string; label: string; base: "dark" | "light" }

export const THEMES: ThemeDef[] = [
  { id: "dark", label: "Min Dark", base: "dark" },
  { id: "light", label: "Min Light", base: "light" },
  { id: "aura-dark", label: "Aura Dark", base: "dark" },
  { id: "ayu-mirage", label: "Ayu Mirage", base: "dark" },
  { id: "bearded-altica", label: "Bearded Altica", base: "dark" },
  { id: "bearded-anthracite", label: "Bearded Anthracite", base: "dark" },
  { id: "bearded-aquarelle-cymbidium", label: "Bearded Aquarelle Cymbidium", base: "dark" },
  { id: "bearded-aquarelle-hydrangea", label: "Bearded Aquarelle Hydrangea", base: "dark" },
  { id: "bearded-aquarelle-lilac", label: "Bearded Aquarelle Lilac", base: "dark" },
  { id: "bearded-arc-blueberry", label: "Bearded Arc Blueberry", base: "dark" },
  { id: "bearded-arc-eggplant", label: "Bearded Arc Eggplant", base: "dark" },
  { id: "bearded-arc-eolstorm", label: "Bearded Arc Eolstorm", base: "dark" },
  { id: "bearded-arc-reversed", label: "Bearded Arc Reversed", base: "dark" },
  { id: "bearded-black-and-amethyst-soft", label: "Bearded Black And Amethyst Soft", base: "dark" },
  { id: "bearded-black-and-amethyst", label: "Bearded Black And Amethyst", base: "dark" },
  { id: "bearded-black-and-diamond-soft", label: "Bearded Black And Diamond Soft", base: "dark" },
  { id: "bearded-black-and-diamond", label: "Bearded Black And Diamond", base: "dark" },
  { id: "bearded-black-and-emerald-soft", label: "Bearded Black And Emerald Soft", base: "dark" },
  { id: "bearded-black-and-emerald", label: "Bearded Black And Emerald", base: "dark" },
  { id: "bearded-black-and-gold-soft", label: "Bearded Black And Gold Soft", base: "dark" },
  { id: "bearded-black-and-gold", label: "Bearded Black And Gold", base: "dark" },
  { id: "bearded-black-and-ruby-soft", label: "Bearded Black And Ruby Soft", base: "dark" },
  { id: "bearded-black-and-ruby", label: "Bearded Black And Ruby", base: "dark" },
  { id: "bearded-coffee-cream", label: "Bearded Coffee Cream", base: "light" },
  { id: "bearded-coffee-reversed", label: "Bearded Coffee Reversed", base: "dark" },
  { id: "bearded-coffee", label: "Bearded Coffee", base: "dark" },
  { id: "bearded-earth", label: "Bearded Earth", base: "dark" },
  { id: "bearded-feat-gold-d-raynh", label: "Bearded Feat Gold D Raynh", base: "dark" },
  { id: "bearded-feat-melle-julie-light", label: "Bearded Feat Melle Julie Light", base: "light" },
  { id: "bearded-feat-melle-julie", label: "Bearded Feat Melle Julie", base: "dark" },
  { id: "bearded-feat-mintshake-d-raynh", label: "Bearded Feat Mintshake D Raynh", base: "light" },
  { id: "bearded-feat-webdevcody", label: "Bearded Feat Webdevcody", base: "dark" },
  { id: "bearded-feat-will", label: "Bearded Feat Will", base: "dark" },
  { id: "bearded-hc-brewing-storm", label: "Bearded Hc Brewing Storm", base: "dark" },
  { id: "bearded-hc-chocolate-espresso", label: "Bearded Hc Chocolate Espresso", base: "dark" },
  { id: "bearded-hc-ebony", label: "Bearded Hc Ebony", base: "dark" },
  { id: "bearded-hc-flurry", label: "Bearded Hc Flurry", base: "light" },
  { id: "bearded-hc-midnight-void", label: "Bearded Hc Midnight Void", base: "dark" },
  { id: "bearded-hc-minuit", label: "Bearded Hc Minuit", base: "dark" },
  { id: "bearded-hc-wonderland-wood", label: "Bearded Hc Wonderland Wood", base: "dark" },
  { id: "bearded-light", label: "Bearded Light", base: "light" },
  { id: "bearded-milkshake-blueberry", label: "Bearded Milkshake Blueberry", base: "light" },
  { id: "bearded-milkshake-mango", label: "Bearded Milkshake Mango", base: "light" },
  { id: "bearded-milkshake-mint", label: "Bearded Milkshake Mint", base: "light" },
  { id: "bearded-milkshake-raspberry", label: "Bearded Milkshake Raspberry", base: "light" },
  { id: "bearded-milkshake-vanilla-banana", label: "Bearded Milkshake Vanilla Banana", base: "light" },
  { id: "bearded-monokai-black", label: "Bearded Monokai Black", base: "dark" },
  { id: "bearded-monokai-metallian", label: "Bearded Monokai Metallian", base: "dark" },
  { id: "bearded-monokai-reversed", label: "Bearded Monokai Reversed", base: "dark" },
  { id: "bearded-monokai-stone", label: "Bearded Monokai Stone", base: "dark" },
  { id: "bearded-monokai-terra", label: "Bearded Monokai Terra", base: "dark" },
  { id: "bearded-oceanic-reversed", label: "Bearded Oceanic Reversed", base: "dark" },
  { id: "bearded-oceanic", label: "Bearded Oceanic", base: "dark" },
  { id: "bearded-oled", label: "Bearded Oled", base: "dark" },
  { id: "bearded-solarized-dark", label: "Bearded Solarized", base: "dark" },
  { id: "bearded-solarized-light", label: "Bearded Solarized Light", base: "light" },
  { id: "bearded-solarized-reversed", label: "Bearded Solarized Reversed", base: "dark" },
  { id: "bearded-solarized", label: "Bearded Solarized", base: "dark" },
  { id: "bearded-stained-blue", label: "Bearded Stained Blue", base: "dark" },
  { id: "bearded-stained-purple", label: "Bearded Stained Purple", base: "dark" },
  { id: "bearded-surprising-blueberry", label: "Bearded Surprising Blueberry", base: "dark" },
  { id: "bearded-surprising-eggplant", label: "Bearded Surprising Eggplant", base: "dark" },
  { id: "bearded-surprising-watermelon", label: "Bearded Surprising Watermelon", base: "dark" },
  { id: "bearded-themanopia", label: "Bearded Themanopia", base: "dark" },
  { id: "bearded-vivid-black", label: "Bearded Vivid Black", base: "dark" },
  { id: "bearded-vivid-light", label: "Bearded Vivid Light", base: "light" },
  { id: "bearded-vivid-purple", label: "Bearded Vivid Purple", base: "dark" },
  { id: "bearded-void", label: "Bearded Void", base: "dark" },
  { id: "catppuccin-mocha", label: "Catppuccin Mocha", base: "dark" },
  { id: "cyberpunk-neon", label: "Cyberpunk Neon", base: "dark" },
  { id: "default-dark", label: "Bearded Arc", base: "dark" },
  { id: "dracula", label: "Dracula", base: "dark" },
  { id: "gruv-box", label: "Gruvbox Soft", base: "dark" },
  { id: "monokai", label: "Monokai", base: "dark" },
  { id: "night-owl", label: "Night Owl", base: "dark" },
  { id: "nord-ford", label: "Nord Frost", base: "dark" },
  { id: "one-dark", label: "One Dark", base: "dark" },
  { id: "rose-milk", label: "Rose Milk", base: "light" },
  { id: "rose-pine", label: "Rose Pine", base: "dark" },
  { id: "sakura-pastel", label: "Sakura Pastel", base: "light" },
  { id: "slate-neutral-dark-schematic", label: "Slate Neutral Dark", base: "dark" },
  { id: "slate-neutral-dark", label: "Slate Neutral Dark", base: "dark" },
  { id: "soft-light", label: "Soft Light", base: "light" },
  { id: "tokyo-night", label: "Tokyo Night", base: "dark" },
  { id: "vscode-dark", label: "Vscode Dark", base: "dark" },
];

export const themeBase = (id: string): "dark" | "light" => THEMES.find((theme) => theme.id === id)?.base ?? "dark";
