import type { CSSProperties } from "react";
import {
  Activity,
  Boxes,
  Braces,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsDown,
  ChevronsUp,
  Copy,
  Code2,
  Database,
  Download,
  FileCode2,
  Eye,
  FolderOpen,
  GitBranch,
  Globe,
  History,
  Key,
  List,
  Keyboard,
  Fullscreen,
  Maximize2,
  Minimize2,
  Moon,
  MoreHorizontal,
  PanelBottom,
  PanelLeft,
  PanelRight,
  Pencil,
  Play,
  Plug,
  Plus,
  Radio,
  Repeat,
  Rows3,
  RefreshCw,
  Save,
  Search,
  Send,
  Settings2,
  SortAsc,
  SortDesc,
  Sparkles,
  Sun,
  Timer,
  Trash2,
  Wand2,
  Workflow,
  WrapText,
  X,
  Zap,
  type LucideIcon,
} from "lucide-react";

const ICONS = {
  activity: Activity,
  braces: Braces,
  check: Check,
  "chevron-down": ChevronDown,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "chevrons-down": ChevronsDown,
  "chevrons-up": ChevronsUp,
  copy: Copy,
  code: Code2,
  database: Database,
  download: Download,
  eye: Eye,
  flow: Workflow,
  folder: FolderOpen,
  fullscreen: Fullscreen,
  github: GitBranch,
  globe: Globe,
  grpc: Boxes,
  history: History,
  key: Key,
  list: List,
  keyboard: Keyboard,
  maximize: Maximize2,
  minify: Minimize2,
  moon: Moon,
  "more-horizontal": MoreHorizontal,
  "panel-bottom": PanelBottom,
  "panel-left": PanelLeft,
  "panel-right": PanelRight,
  pencil: Pencil,
  play: Play,
  plug: Plug,
  plus: Plus,
  refresh: RefreshCw,
  repeat: Repeat,
  rows: Rows3,
  request: FileCode2,
  save: Save,
  search: Search,
  send: Send,
  settings: Settings2,
  "sort-asc": SortAsc,
  "sort-desc": SortDesc,
  sparkles: Sparkles,
  sun: Sun,
  timer: Timer,
  trash: Trash2,
  wand: Wand2,
  wrap: WrapText,
  ws: Radio,
  x: X,
  zap: Zap,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICONS;

interface Props {
  name: IconName;
  size?: number;
  style?: CSSProperties;
  className?: string;
}

export function Icon({ name, size = 15, style, className }: Props) {
  const Component = ICONS[name];
  return <Component size={size} strokeWidth={1.8} style={{ flex: "none", ...style }} className={className} aria-hidden />;
}
